---
apiVersion: v1
kind: Service
metadata:
    name: back-end

spec:
    type: LoadBalancer
    ports:
        - targetPort: 80
          port: 80
          NodePort: 30008

    selector:
        app: my-app
        type: back-end
