FROM python:3.11.0-slim

RUN apt-get update && apt-get install make git graphviz -y --no-install-recommends

ARG USERNAME=vorph
ARG USER_UID=1000
ARG USER_GID=1000


RUN groupadd -g $USER_GID -o $USERNAME && useradd -m -u $USER_UID -g $USER_GID -o -s /bin/bash $USERNAME

USER $USERNAME

ENV PATH "$PATH:/home/$USERNAME/.local/bin"

RUN python -m pip install --upgrade pip
ENV PATH "$PATH:/usr/lib/python3.9/dist-packages"

WORKDIR /home/$USERNAME

COPY requirements.txt .

RUN /bin/bash -c "python -m pip install -r requirements.txt"
# 8000 for mkdocs
EXPOSE 8000
