---
jobs:
    - job: Linux
      pool:
          vmImage: ubuntu-20.04
      steps:
          - bash: echo "Hello Ubuntu"

          - template: steps-template.yaml

    - job: Windows
      pool:
          vmImage: windows-latest
      steps:
          - bash: echo "Hello Windows"
