---
name: Build & Deploy
on: [push, pull_request]

jobs:
    update-docs:
        # update stack only if admin user
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.9'
            - name: Install dependencies
              run: |
                  python -m pip install -r requirements.txt
            - name: Deploy documentation
              run: mkdocs gh-deploy --force

    test-build-docs:
        # test build doc stack if dependabot
        if: ${{ github.actor == 'dependabot[bot]' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: '3.9'
            - name: Install dependencies
              run: |
                  python -m pip install -r requirements.txt
            - name: Deploy documentation
              run: mkdocs build
